FROM python:3.10-slim

WORKDIR /app

# Copier le backend et le requirements
COPY backend/ ./backend
COPY requirements.txt .

# Installer les dépendances
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

# Exposer le port de l'API
EXPOSE 8000

# Commande de lancement
CMD ["uvicorn", "backend.api:app", "--host", "0.0.0.0", "--port", "8000"]
